version: '3.7'

services:
  rtmp:
    build: .
    volumes:
      - records:/records
      - ./rtmp.conf:/etc/nginx/nginx.conf:ro
      - /etc/localtime:/etc/localtime
    networks:
      - traefik
    ports:
      - 1935:1935
    labels:
      - 'traefik.enable=true'
      - 'traefik.network=traefik'
      - 'traefik.frontend.rule=Host:rtmp.${DOMAINNAME}'
      - 'traefik.records.port=80'
      - 'traefik.rtmp.port=1935'
      - 'traefik.rtmp.protocol=rtmp'

volumes:
  records:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/data/docker-host/rtmp-server/records

networks:
  traefik:
    external: true
