version: '3.7'

services:
  site:
    image: nginx
    restart: always
    container_name: aurelien.arino.io
    expose:
      - 80
    labels:
      - "traefik.frontend.rule=Host:aurelien.${DOMAINNAME}"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.network=traefik"
    volumes:
      - type: bind
        source: ./files
        target: /usr/share/nginx/html
    networks:
      - traefik

networks:
  traefik:
    external: true
